apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: chatbot-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: chatbot
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
